### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by pretsell**
Use custom title for title

### CODE REVIEW

**Comment by PutterPlace** [comment]
I'm going through all PRs right now, and thanks for this one! I have no clue how I missed it. I must've accidentally undid that change at some point before a commit, or before the first commit, cuz I swear I had it there. :-P

Anyways, I'll get this merged in a bit. I'm working on some other stuff simultaneously right now.

**Comment by pretsell** [comment]
double check this please XD

**Comment by PutterPlace** [comment]
I checked it a long while back, but just recently got around to merging it. This project is pretty much dead now, but I figured I'd merge the PRs for the sake of completeness. :-)

**Comment by pretsell** [comment]
Good times at the times :D

**Pull request merged**
